version: '2'

services:
        app:
                image: eclipse-mosquitto:2.0
                volumes:
                        - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
                        - ./cert:/cert
                ports:
                        - "1883:1883"
                        - "9001:9001"
