[constant]
harware = "usb_device" # "sparkplug_hat_dead", "max_GNSS"
freq = 5  # every x second
name = "Trolly_1"

[constant.gps]
#port = "/dev/ttyACM1" #
port = "/dev/ttyUSB0"
type = "GPS" # could also be GPS GNSS

[constant.cellData]

[mqtt]
broker = "mqtt.docker.local" #'mqtt.docker.local'
port = 1883
retainLast = true
qos = 0


[mqtt.publish]
topic = "Transport_tracking/{constant.name}/"

[sqlite3]
dataBaseName = 'TRACKING'
method = "api" # api or fileLocal
path = "http://database.docker.local:8800" #local path is 'data/tracking.db'
